#!/usr/bin/env node
/**
 * Prebuild script for Lite builds
 * Modifies app.json to set different app name and package names for lite builds
 * This allows full and lite versions to coexist on the same device
 * Also ensures native code is regenerated with new package names
 */

const fs = require('fs');
const path = require('path');

// Ignore command line arguments (EAS may pass --platform, etc.)
// We only use environment variables, so we can safely ignore all args
const args = process.argv.slice(2);
if (args.length > 0) {
  console.log(`ℹ️  Ignoring command line arguments: ${args.join(' ')}`);
}

// Check if this is a lite build
// EAS sets EAS_BUILD_PROFILE, and we also check the environment variable
const easProfile = process.env.EAS_BUILD_PROFILE || '';
const enableMasterminds = process.env.EXPO_PUBLIC_ENABLE_MASTERMINDS;
const isLiteBuild = enableMasterminds === 'false' || easProfile.includes('lite');

console.log('🔍 Prebuild script check:');
console.log(`   EAS_BUILD_PROFILE: ${easProfile}`);
console.log(`   EXPO_PUBLIC_ENABLE_MASTERMINDS: ${enableMasterminds}`);
console.log(`   Is Lite Build: ${isLiteBuild}`);

if (!isLiteBuild) {
  console.log('ℹ️  Not a lite build, skipping app.json modification');
  process.exit(0);
}

// Wrap the main logic in try-catch to ensure we always exit properly
try {

console.log('🔧 Starting Lite build prebuild...');

const appJsonPath = path.join(__dirname, '..', 'app.json');

let appJson;
try {
  appJson = JSON.parse(fs.readFileSync(appJsonPath, 'utf8'));
} catch (error) {
  console.error('❌ Error reading app.json:', error);
  process.exit(1);
}

// Backup original values (for reference)
const originalName = appJson.expo.name;
const originalPackage = appJson.expo.android.package;
const originalBundleId = appJson.expo.ios.bundleIdentifier;
const originalSlug = appJson.expo.slug;
const originalScheme = appJson.expo.scheme;

// Modify app name for lite builds
appJson.expo.name = 'Balance Seekr Lite';

// Modify package names to allow coexistence
appJson.expo.android.package = 'com.balanceseekr.app.lite';
appJson.expo.ios.bundleIdentifier = 'com.balanceseekr.app.lite';

// Keep slug the same for EAS project compatibility (slug must match project ID)
// appJson.expo.slug = 'balance-seekr-lite'; // Commented out to avoid EAS project mismatch

// Modify scheme for lite builds
appJson.expo.scheme = 'balanceseekrlite';

// CRITICAL: Disable Masterminds in app.json extra field
if (!appJson.expo.extra) {
  appJson.expo.extra = {};
}
appJson.expo.extra.enableMasterminds = false;

// Write back to app.json
try {
  fs.writeFileSync(appJsonPath, JSON.stringify(appJson, null, 2));
  console.log('✅ Successfully wrote app.json');
} catch (error) {
  console.error('❌ Error writing app.json:', error);
  process.exit(1);
}

console.log('✅ Modified app.json for Lite build:');
console.log(`   App Name: ${originalName} → ${appJson.expo.name}`);
console.log(`   Android Package: ${originalPackage} → ${appJson.expo.android.package}`);
console.log(`   iOS Bundle ID: ${originalBundleId} → ${appJson.expo.ios.bundleIdentifier}`);
console.log(`   Slug: ${originalSlug} (unchanged for EAS compatibility)`);
console.log(`   Scheme: ${originalScheme} → ${appJson.expo.scheme}`);
console.log(`   enableMasterminds: ${appJson.expo.extra?.enableMasterminds} (DISABLED)`);

// Note: EAS will handle native code regeneration automatically
// We don't need to remove android/ios folders as EAS will regenerate them
console.log('✅ Prebuild complete. Native code will be regenerated by EAS with new package names.');

} catch (error) {
  console.error('❌ Fatal error in prebuild script:', error);
  process.exit(1);
}

// Explicitly exit with success code
process.exit(0);

